<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="bootstrap admin template">
    <meta name="author" content="">
    
    <title>Apresentação Geoinova</title>
    
    <!-- favicon -->
    <link rel="apple-touch-icon" href="/templates/remark/topicon/assets/images/apple-touch-icon.png">
    <link rel="shortcut icon" href="/templates/remark/topicon/assets/images/favicon.ico">
    
    <!-- bootstrap -->    
    <link rel="stylesheet" href="/templates/remark/global/css/bootstrap.min.css">
    <link rel="stylesheet" href="/templates/remark/global/css/bootstrap-extend.min.css">
    
    <!-- styles -->
    <link rel="stylesheet" href="/templates/remark/topicon/assets/css/site.min.css">
    <link rel="stylesheet" href="/templates/remark/global/vendor/animsition/animsition.css">
    <link rel="stylesheet" href="/templates/remark/global/vendor/asscrollable/asScrollable.css">
    <link rel="stylesheet" href="/templates/remark/global/vendor/switchery/switchery.css">
    <link rel="stylesheet" href="/templates/remark/global/vendor/intro-js/introjs.css">
    <link rel="stylesheet" href="/templates/remark/global/vendor/slidepanel/slidePanel.css">
    <link rel="stylesheet" href="/templates/remark/global/vendor/flag-icon-css/flag-icon.css">
    <link rel="stylesheet" href="/templates/remark/global/vendor/waves/waves.css">
    <link rel="stylesheet" href="/templates/remark/topicon/assets/examples/css/pages/lockscreen.css">
    
    <!-- Fonts -->
    <link rel="stylesheet" href="/templates/remark/global/fonts/material-design/material-design.min.css">
    <link rel="stylesheet" href="/templates/remark/global/fonts/brand-icons/brand-icons.min.css">    
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
    
    <script src="/templates/remark/global/vendor/modernizr/modernizr.js"></script>
    <script src="/templates/remark/global/vendor/breakpoints/breakpoints.js"></script>
       
    <!-- pillar framework -->
    <script type="text/javascript" src="http://cdn-pillar.s3.amazonaws.com/bin/jquery.js"></script>    
    <script type="text/javascript" src="http://cdn-pillar.s3.amazonaws.com/v2.2/pillar.develop.js?v1.03" app="/modules/app.js?v1" config="/modules/config.js"></script>
</head>

<body>
    
    <div at="homepage"></div>
    
    <!-- Core  -->
    <script src="/templates/remark/global/vendor/jquery/jquery.js"></script>
    <script src="/templates/remark/global/vendor/bootstrap/bootstrap.js"></script>
    <script src="/templates/remark/global/vendor/animsition/animsition.js"></script>
    <script src="/templates/remark/global/vendor/asscroll/jquery-asScroll.js"></script>
    <script src="/templates/remark/global/vendor/mousewheel/jquery.mousewheel.js"></script>
    <script src="/templates/remark/global/vendor/asscrollable/jquery.asScrollable.all.js"></script>
    <script src="/templates/remark/global/vendor/ashoverscroll/jquery-asHoverScroll.js"></script>
    <script src="/templates/remark/global/vendor/waves/waves.js"></script>
    
    <!-- Plugins -->
    <script src="/templates/remark/global/vendor/switchery/switchery.min.js"></script>
    <script src="/templates/remark/global/vendor/intro-js/intro.js"></script>
    <script src="/templates/remark/global/vendor/screenfull/screenfull.js"></script>
    <script src="/templates/remark/global/vendor/slidepanel/jquery-slidePanel.js"></script>
    <script src="/templates/remark/global/vendor/jquery-placeholder/jquery.placeholder.js"></script>
    
    <!-- Scripts -->
    <script src="/templates/remark/global/js/core.js"></script>
    <script src="/templates/remark/topicon/assets/js/site.js"></script>
    <script src="/templates/remark/topicon/assets/js/sections/menu.js"></script>
    <script src="/templates/remark/topicon/assets/js/sections/menubar.js"></script>
    <script src="/templates/remark/topicon/assets/js/sections/sidebar.js"></script>
    <script src="/templates/remark/global/js/configs/config-colors.js"></script>
    <script src="/templates/remark/topicon/assets/js/configs/config-tour.js"></script>
    <script src="/templates/remark/global/js/components/asscrollable.js"></script>
    <script src="/templates/remark/global/js/components/animsition.js"></script>
    <script src="/templates/remark/global/js/components/slidepanel.js"></script>
    <script src="/templates/remark/global/js/components/switchery.js"></script>
    <script src="/templates/remark/global/js/components/tabs.js"></script>
    <script src="/templates/remark/global/js/components/jquery-placeholder.js"></script>
    <script src="/templates/remark/global/js/components/animate-list.js"></script>  
</body>

</html>