<div class="conteiner-result-search">
  <div class="page-content page-content-search">
    <!-- Panle List -->
    <div class="panel">
      <div class="panel-heading">
        <h3 class="panel-title">Projeto Alpha</h3>
      </div>
      <div class="panel-body container-fluid">
        <div class="row row-lg">

          <div class="col-sm-12 col-lg-12">
            <div class="example table-responsive">
              <table class="table">
                <tbody>
                  <tr>
                    <td><a class="avatar" href="javascript:void(0)">
                      <img class="img-responsive" src="http://bigdesignevents.com/portal/wp-content/uploads/2013/10/nab-a-nerd.png" alt="...">
                    </a></td>
                    <td>Manoel Neco</td>
                    <td>Resolução de tela</td>
                    <td>20/05/2016</td>
                  </tr>
                  <tr>
                    <td><a class="avatar" href="javascript:void(0)">
                      <img class="img-responsive" src="http://www.linkirado.net/img_post/link-irado-2fbeac43716777aec1eabd8fb55352d2.jpg" alt="...">
                    </a></td>
                    <td>Nelcino Júnior</td>
                    <td>Resolução de tela</td>
                    <td>21/05/2016</td>
                  </tr>

                  <tr>
                    <td><a class="avatar" href="javascript:void(0)">
                      <img class="img-responsive" src="http://bigdesignevents.com/portal/wp-content/uploads/2013/10/nab-a-nerd.png" alt="...">
                    </a></td>
                    <td>Manoel Neco</td>
                    <td>Teste de programação</td>
                    <td>20/05/2016</td>
                  </tr>
                  <tr>
                    <td><a class="avatar" href="javascript:void(0)">
                      <img class="img-responsive" src="http://www.linkirado.net/img_post/link-irado-2fbeac43716777aec1eabd8fb55352d2.jpg" alt="...">
                    </a></td>
                    <td>Nelcino Júnior</td>
                    <td>Sem ideia temos que melhorar</td>
                    <td>21/05/2016</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End Panle List -->
  </div>


  <div class="page-content page-content-search">
    <!-- Panle List -->
    <div class="panel">
      <div class="panel-heading">
        <h3 class="panel-title">Projeto Aguias Software</h3>
      </div>
      <div class="panel-body container-fluid">
        <div class="row row-lg">

          <div class="col-sm-12 col-lg-12">
            <div class="example table-responsive">
              <table class="table">
                <tbody>
                  <tr>
                    <td><a class="avatar" href="javascript:void(0)">
                      <img class="img-responsive" src="http://bigdesignevents.com/portal/wp-content/uploads/2013/10/nab-a-nerd.png" alt="...">
                    </a></td>
                    <td>Manoel Neco</td>
                    <td>Resolução de tela</td>
                    <td>20/05/2016</td>
                  </tr>
                  <tr>
                    <td><a class="avatar" href="javascript:void(0)">
                      <img class="img-responsive" src="http://www.linkirado.net/img_post/link-irado-2fbeac43716777aec1eabd8fb55352d2.jpg" alt="...">
                    </a></td>
                    <td>Nelcino Júnior</td>
                    <td>Resolução de tela</td>
                    <td>21/05/2016</td>
                  </tr>

                  <tr>
                    <td><a class="avatar" href="javascript:void(0)">
                      <img class="img-responsive" src="http://bigdesignevents.com/portal/wp-content/uploads/2013/10/nab-a-nerd.png" alt="...">
                    </a></td>
                    <td>Manoel Neco</td>
                    <td>Teste de programação</td>
                    <td>20/05/2016</td>
                  </tr>
                  <tr>
                    <td><a class="avatar" href="javascript:void(0)">
                      <img class="img-responsive" src="http://www.linkirado.net/img_post/link-irado-2fbeac43716777aec1eabd8fb55352d2.jpg" alt="...">
                    </a></td>
                    <td>Nelcino Júnior</td>
                    <td>Sem ideia temos que melhorar</td>
                    <td>21/05/2016</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End Panle List -->
  </div>
</div>