<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description" content="bootstrap admin template">
  <meta name="author" content="">
  <title>Apresentação Geoinova</title>
  <link rel="apple-touch-icon" href="/remark/topicon/assets/images/apple-touch-icon.png">
  <link rel="shortcut icon" href="/remark/topicon/assets/images/favicon.ico">
  <!-- Stylesheets -->
  <link rel="stylesheet" href="/remark/global/css/bootstrap.min.css">
  <link rel="stylesheet" href="/remark/global/css/bootstrap-extend.min.css">
  <link rel="stylesheet" href="/remark/topicon/assets/css/site.min.css">
  <!-- Plugins -->
  <link rel="stylesheet" href="/remark/global/vendor/animsition/animsition.css">
  <link rel="stylesheet" href="/remark/global/vendor/asscrollable/asScrollable.css">
  <link rel="stylesheet" href="/remark/global/vendor/switchery/switchery.css">
  <link rel="stylesheet" href="/remark/global/vendor/intro-js/introjs.css">
  <link rel="stylesheet" href="/remark/global/vendor/slidepanel/slidePanel.css">
  <link rel="stylesheet" href="/remark/global/vendor/flag-icon-css/flag-icon.css">
  <link rel="stylesheet" href="/remark/global/vendor/waves/waves.css">
  <link rel="stylesheet" href="/remark/topicon/assets/examples/css/pages/lockscreen.css">
  <!-- Fonts -->
  <link rel="stylesheet" href="/remark/global/fonts/material-design/material-design.min.css">
  <link rel="stylesheet" href="/remark/global/fonts/brand-icons/brand-icons.min.css">



  <link rel="stylesheet" href="/geoinova/presentation/presentation.css">
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
  <!--[if lt IE 9]>
    <script src="/remark/global/vendor/html5shiv/html5shiv.min.js"></script>
    <![endif]-->
  <!--[if lt IE 10]>
    <script src="/remark/global/vendor/media-match/media.match.min.js"></script>
    <script src="/remark/global/vendor/respond/respond.min.js"></script>
    <![endif]-->
    <!-- Scripts -->
    <script src="/remark/global/vendor/modernizr/modernizr.js"></script>
    <script src="/remark/global/vendor/breakpoints/breakpoints.js"></script>
    <script>
    Breakpoints();
    </script>
  </head>
  <body class="presentation layout-full page-dark">
  <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <!-- Page -->
        <div class="page animsition vertical-align text-center" data-animsition-in="fade-in"
        data-animsition-out="fade-out">
        <div class="page-content vertical-align-middle">
          <h4 class="presentation-title">
            Sabia que 25% do território nacional está localizado no 
            território do Brasil Central?
          </h4>

          <div class="input-group presentation-input">
            <input type="text" class="form-control last"  name=""
            placeholder="Digite o cenário a ser pesquisado">
            <span class="input-group-btn ">
              <button class="btn btn-primary">
                <i class="icon md-menu" aria-hidden="true"></i>
              </button>
            </span>
          </div>

          <div class="dropdown open navbar-mega">
            <ul class="dropdown-menu" role="menu">
              <li role="presentation">
                <div class="mega-content">
                  <div class="row">
                    <div class="col-sm-4">
                      <div class="col-sm-6">
                        <h5>Cidades</h5>
                        <ul class="list-group list-group-dividered list-group-full presentation-list presentation-list-cidades">
                          <li class="list-group-item">Goiânia</li>
                          <li class="list-group-item">Goianira</li>
                          <li class="list-group-item">Goiás Velho</li>
                          <li class="list-group-item">Goiatuba</li>
                        </ul>
                      </div>
                      <div class="col-sm-6">
                        <h5>Produtos</h5>
                        <ul class="list-group list-group-dividered list-group-full presentation-list presentation-list-produtos">
                          <li class="list-group-item">Goiaba</li>
                          <li class="list-group-item">Doce de goiaba</li>
                          <li class="list-group-item">Transporte de goiaba</li>
                          <li class="list-group-item">Goiabeira</li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-sm-4">
                      <h5 >Painel
                      </h5>
                      <div class="presentation-tile-painel-center"></div>
                      <ul class="blocks-3">
                        <li>
                          <a class="thumbnail margin-0" href="javascript:void(0)">
                            <img class="width-full" src="/remark/global/photos/placeholder.png" alt="..." />
                          </a>
                        </li>
                        <li>
                          <a class="thumbnail margin-0" href="javascript:void(0)">
                            <img class="width-full" src="/remark/global/photos/placeholder.png" alt="..." />
                          </a>
                        </li>
                        <li>
                          <a class="thumbnail margin-0" href="javascript:void(0)">
                            <img class="width-full" src="/remark/global/photos/placeholder.png" alt="..." />
                          </a>
                        </li>
                        <li>
                          <a class="thumbnail margin-0" href="javascript:void(0)">
                            <img class="width-full" src="/remark/global/photos/placeholder.png" alt="..." />
                          </a>
                        </li>
                        <li>
                          <a class="thumbnail margin-0" href="javascript:void(0)">
                            <img class="width-full" src="/remark/global/photos/placeholder.png" alt="..." />
                          </a>
                        </li>
                        <li>
                          <a class="thumbnail margin-0" href="javascript:void(0)">
                            <img class="width-full" src="/remark/global/photos/placeholder.png" alt="..." />
                          </a>
                        </li>
                      </ul>
                    </div>
                    <div class="col-sm-4">
                      <h5>Cenários</h5>
                      <ul class="list-group list-group-dividered list-group-full presentation-list presentation-list-cenario">
                        <li class="list-group-item">Os melhores municipios para investir</li>
                        <li class="list-group-item">Os melhores municipios para exportação de café</li>
                        <li class="list-group-item">Os melhores municipios para exportação de soja</li>
                        <li class="list-group-item">Os melhores municipios para exportação de abacaxi</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>




          <div class="media-center">
            <h5 class="presentation-links-speed">LINKS RÁPIDOS</h5>
            <button type="button" class="btn btn-floating btn-primary presentation-btn-links">
              <i class="icon md-seat" aria-hidden="true"></i>
            </button>

            <button type="button" class="btn btn-floating btn-danger presentation-btn-links">
              <i class="icon md-subway" aria-hidden="true"></i>
            </button>

            <button type="button" class="btn btn-floating  btn-warning presentation-btn-links">
              <i class="icon md-gas-station" aria-hidden="true"></i>
            </button>

            <button type="button" class="btn btn-floating btn-primary presentation-btn-links">
              <i class="icon md-lamp" aria-hidden="true"></i>
            </button>

            <button type="button" class="btn btn-floating btn-success presentation-btn-links">
              <i class="icon md-navigation" aria-hidden="true"></i>
            </button>

            <button type="button" class="btn btn-floating btn-danger presentation-btn-links">
              <i class="icon md-pin-drop" aria-hidden="true"></i>
            </button>

          </div>
          <footer class="page-copyright page-copyright-inverse">
            <p>Geoinova Soluções</p>
            <p>© 2010. Expertise em Geotecnologia</p>
          </footer>
        </div>
      </div>
      <!-- End Page -->
      <!-- Core  -->
      <script src="/remark/global/vendor/jquery/jquery.js"></script>
      <script src="/remark/global/vendor/bootstrap/bootstrap.js"></script>
      <script src="/remark/global/vendor/animsition/animsition.js"></script>
      <script src="/remark/global/vendor/asscroll/jquery-asScroll.js"></script>
      <script src="/remark/global/vendor/mousewheel/jquery.mousewheel.js"></script>
      <script src="/remark/global/vendor/asscrollable/jquery.asScrollable.all.js"></script>
      <script src="/remark/global/vendor/ashoverscroll/jquery-asHoverScroll.js"></script>
      <script src="/remark/global/vendor/waves/waves.js"></script>
      <!-- Plugins -->
      <script src="/remark/global/vendor/switchery/switchery.min.js"></script>
      <script src="/remark/global/vendor/intro-js/intro.js"></script>
      <script src="/remark/global/vendor/screenfull/screenfull.js"></script>
      <script src="/remark/global/vendor/slidepanel/jquery-slidePanel.js"></script>
      <script src="/remark/global/vendor/jquery-placeholder/jquery.placeholder.js"></script>
      <!-- Scripts -->
      <script src="/remark/global/js/core.js"></script>
      <script src="/remark/topicon/assets/js/site.js"></script>
      <script src="/remark/topicon/assets/js/sections/menu.js"></script>
      <script src="/remark/topicon/assets/js/sections/menubar.js"></script>
      <script src="/remark/topicon/assets/js/sections/sidebar.js"></script>
      <script src="/remark/global/js/configs/config-colors.js"></script>
      <script src="/remark/topicon/assets/js/configs/config-tour.js"></script>
      <script src="/remark/global/js/components/asscrollable.js"></script>
      <script src="/remark/global/js/components/animsition.js"></script>
      <script src="/remark/global/js/components/slidepanel.js"></script>
      <script src="/remark/global/js/components/switchery.js"></script>
      <script src="/remark/global/js/components/tabs.js"></script>
      <script src="/remark/global/js/components/jquery-placeholder.js"></script>
      <script src="/remark/global/js/components/animate-list.js"></script>
      <script>
      (function(document, window, $) {
        'use strict';
        var Site = window.Site;
        $(document).ready(function() {
          Site.run();
        });
      })(document, window, jQuery);
      </script>
    </body>
    </html>