<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description" content="bootstrap admin template">
  <meta name="author" content="">
  <title>GoProject</title>
  <link rel="apple-touch-icon" href="templates/remark/images/apple-touch-icon.png">
  <link rel="shortcut icon" href="templates/remark/images/favicon.ico">
  <!-- Stylesheets -->
  <link rel="stylesheet" href="templates/remark/global/css/bootstrap.min.css">
  <link rel="stylesheet" href="templates/remark/global/css/bootstrap-extend.min.css">
  <link rel="stylesheet" href="templates/remark/global/css/site.css">
  <!-- Fonts -->
  <link rel="stylesheet" href="templates/remark/global/fonts/material-design/material-design.min.css">
  <link rel="stylesheet" href="templates/remark/global/fonts/brand-icons/brand-icons.min.css">
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
</head>
<body class="site-navbar-small dashboard">
  <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <nav class="top-search site-navbar navbar navbar-default navbar-fixed-top navbar-mega navbar-inverse navbar-inverse bg-blue-600"
        role="navigation">
        <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-target="#site-navbar-collapse"
         data-toggle="collapse">
         <i class="icon md-more" aria-hidden="true"></i>
       </button>
       <a class="navbar-brand navbar-brand-center" href="/index.html">
        <!-- <img class="navbar-brand-logo navbar-brand-logo-normal" src="templates/remark/images/logo.png"
        title="Remark">
        <img class="navbar-brand-logo navbar-brand-logo-special" src="templates/remark/images/logo-blue.png"
        title="Remark"> -->
        <span class="navbar-brand-text title-top"> GoProject</span>
      </a>
    </div>
    <div class="navbar-container container-fluid">
      <div class="search-container">
        <div class="form-group">
          <input type="text" class="form-control input-top-search" name="" placeholder="Pesquisa">
          <button type="submit" class="input-search-btn btn-top-search"><i class="icon md-search" aria-hidden="true"></i></button>
        </div>
      </div>

      <div class="content-list">
        <div class="conteiner-list">
          <ul class="ul-list">
            <li>Pesquisa 1</li>
            <li>pesquisa 2</li>
            <li>pesquisa 3</li>
            <li>pesquisa 4</li>
          </ul>
        </div>
      </div>

    </div>
  </nav>
  
  <div id="teste">
    <?= $this->content ?>
  </div>
  


  <!-- Footer -->
  <footer class="site-footer">
    <div class="site-footer-legal">© 2016 <a href="http://themeforest.net/item/remark-responsive-bootstrap-admin-template/11989202">AguiaSoftware</a></div>
    <div class="site-footer-right">
      Faça seu projeto, com facilidade e qualidade <i class="red-600 icon md-favorite"></i> use Goproject</a>
    </div>
  </footer>
  <!-- Core  -->
  <?= $this->addScript('templates/remark/global/js/jquery.js') ?>
  <?= $this->addScript('templates/remark/global/js/bootstrap.js') ?>
  <?= $this->addScript('modules/search/search.js') ?>
  <!-- Scripts -->
  <?= $this->addScript('templates/remark/global/js/core.js') ?>
</body>
</html>